### ISSUE TITLE
Presenter page is empty on page load

### ISSUE THREAD

**Issue by serge1peshcoff** [lesteenman/openslides-clicker#12]
I'm facing this every time I use this plugin: when the page is loaded, it is empty. If I will open the preview on the right side, everything will appear, but it would be cool if I won't have to open/close the preview for plugin to start working.

I've no idea on why it happens, will write more details here a little bit later.

**Comment by lesteenman** [comment]
I've noticed this before as well. If you figure anything relevant out, please let us know here.

**Comment by serge1peshcoff** [comment]
Okay, what I've found out so far is it most likely isn't displayed because `$scope.mode` is neither `pdf` nor `none`. Check out the first screenshot, when it is not displayed (look at the inspector):

![image](https://user-images.githubusercontent.com/1060257/39725585-013534c2-5255-11e8-9421-29a932aa3731.png)

and the second one, where everything is displayed:
![image](https://user-images.githubusercontent.com/1060257/39725594-09b1a11c-5255-11e8-992c-1dd5f4d7e9a0.png)

**Comment by serge1peshcoff** [comment]
When I've changed the second `ng-if` inside the template from `mode === 'none'` to `mode !== 'pdf'`, the 'No controllable media bla-bla-bla' was shown (the projected file was PDF). And after ~15-30 seconds of waiting, the PDF and the iframe was displayed.
That is actually weird, since `$scope.mode` is right, as I added some `console.log` statements, and here is the result:

![image](https://user-images.githubusercontent.com/1060257/39726242-21e40c78-5257-11e8-87bf-3a5d1eb3bf55.png)

**Comment by serge1peshcoff** [comment]
Lol, adding `$scope.$apply()` to `updatePresentedMediafiles()` apparently solved it, here is what I've changed and now it works for me:

```
setTimeout(function() {
        if (!mediafile) {
            $scope.mode = 'none';
        } else if (mediafile.is_video) {
            $scope.mode = 'none';
        } else if (mediafile.is_image) {
            $scope.mode = 'none';
        } else if (mediafile.is_pdf || mediafile.is_presentable) {
            $scope.mode = 'pdf';
        } else {
            console.log('no match!')
        }
        console.log('set scope', $scope.mode)
        $scope.$apply(); // the only LOC that matters
        console.log('updated');
}, 0);
```

I will make a PR tomorrow on that.

**Comment by lesteenman** [comment]
Hmm. Looking at some documentation (I'm not very experienced with Angular), I think it could also be fixed by not wrapping it in a `setTimeout`, but delaying that some other way. For now, however, this should be fine as well.
