### ISSUE TITLE
Fix slide counter switching

### ISSUE THREAD

**Issue by serge1peshcoff** [lesteenman/openslides-clicker#8]
So I've faced a problem.
For example, I have the PDF with 5 pages, and I'm on slide 1, I press the 'left' button and it sends me to slide 0 and then to -1. And also if I'm on page 5 and I press 'right' I go to number 6. That is totally not appropriate on stage, since if the person will click the wrong button, he will need to press the right one 2 times and it's inconvenient.

We should prevent slide changing when the new slide would not be in [1; presentations slide count] interval and probably show some warning like "this is the first slide" or "this is the last slide".

(mostly writing it to myself to not forget a thing, I'm gonna make a PR on this in a week, since I need this to be fixed a lot).

**Comment by lesteenman** [comment]
Hmm, apparently I have not tested this earlier. I pretty much assumed OpenSlides would not allow you to move to those slides if they did not exist.

**Comment by serge1peshcoff** [comment]
okay, I've fixed this, I will make a PR after the end of the Agora (after 29.04)
