### ISSUE TITLE
Display the message when the button is pressed

### ISSUE THREAD

**Issue by serge1peshcoff** [lesteenman/openslides-clicker#9]
Since sometimes the presentation is displayed with delays (because of the big size) it's confusing for the presenter sometimes because when they use clicker, they don't know if the clicker didn't work (especially the infrared ones) or it's the delay within OpenSlides when it's trying to load the mediafile.

My proposal is to add some kind of message that would show that some button was pressed, so it would be more clear.

(again, this is mostly for me, since I'm gonna make a PR on it, but I'm interested in your opinion @lesteenman, what do you think about it?)

**Comment by lesteenman** [comment]
I think a material-style 'snackbar' would be best for this, but I'm not sure if OS has something for ephemeral messages already. See https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs, especially the part on desktop/tablet snackbars.

Simply displaying a message in the page itself could also work, but will not be nearly as visible from the corner of your eye as a snackbar will. A snackbar is also designed to be used with messages that will be gone quickly, even if you get several in quick succession. It could e.g. show just what button is pressed, or it could include what page it changes to.

**Comment by serge1peshcoff** [comment]
@lesteenman I agree that it would look really nice, but since there is already a support for messages at the bottom of the screen, what are you thinking about me implementing it using messages? That would also look nice and we won't need extra dependencies for that, and anyway, things like this are implemented as messages anyway.

**Comment by lesteenman** [comment]
Do you have an example of what the bottom messages look like? I don't currently have a dev environment set up. If they're similar in function, then the built-in way would definitely be preferred. The main point is that it's something that clearly changes on-screen, and goes away after a short period of time.

**Comment by serge1peshcoff** [comment]
@lesteenman sorry for the late reply.
For example, if you will open the browser and then shut down the server, the message will appear at the bottom of the page. I'm attaching the screenshot of how it looks like:

![image](https://user-images.githubusercontent.com/1060257/39672839-717bdfd6-513a-11e8-835b-6bf9f041199c.png)

**Comment by lesteenman** [comment]
That looks fine to me. Just make sure the message is short and clear, and disappears after, I think, 3 seconds. If it lingers too long, you can't see when you click the next button (because the message is still there).
